<?php
function read(){

  $ar=fopen("download/download_link(DO NOT EDIT THIS FILE!).txt","r") or
    die("No se pudo abrir el archivo");
  while (!feof($ar))
  {
    $linea=fgets($ar);
    return $linea;
  }
  fclose($ar);
}

?>